// Decompiled with JetBrains decompiler
// Type: djack.RogueSurvivor.Gameplay.GameImages
// Assembly: RogueSurvivor, Version=0.9.0.0, Culture=neutral, PublicKeyToken=null
// MVID: D2AE4FAE-2CA8-43FF-8F2F-59C173341976
// Assembly location: C:\Private.app\RS9Alpha.Hg\RogueSurvivor.exe

using djack.RogueSurvivor.Engine;
using System;
using System.Collections.Generic;
using System.Drawing;

namespace djack.RogueSurvivor.Gameplay
{
  internal static class GameImages
  {
    private static readonly Dictionary<string, Image> s_Images = new Dictionary<string, Image>();
    private static readonly Dictionary<string, Image> s_GrayLevelImages = new Dictionary<string, Image>();
    private const float GRAYLEVEL_DIM_FACTOR = 0.55f;
    public const string ACTIVITY_CHASING = "Activities\\chasing";
    public const string ACTIVITY_CHASING_PLAYER = "Activities\\chasing_player";
    public const string ACTIVITY_TRACKING = "Activities\\tracking";
    public const string ACTIVITY_FLEEING = "Activities\\fleeing";
    public const string ACTIVITY_FLEEING_FROM_EXPLOSIVE = "Activities\\fleeing_explosive";
    public const string ACTIVITY_FOLLOWING = "Activities\\following";
    public const string ACTIVITY_FOLLOWING_ORDER = "Activities\\following_order";
    public const string ACTIVITY_FOLLOWING_PLAYER = "Activities\\following_player";
    public const string ACTIVITY_SLEEPING = "Activities\\sleeping";
    public const string ICON_BLAST = "Icons\\blast";
    public const string ICON_CAN_TRADE = "Icons\\can_trade";
    public const string ICON_THREAT_SAFE = "Icons\\threat_safe";
    public const string ICON_THREAT_DANGER = "Icons\\threat_danger";
    public const string ICON_THREAT_HIGH_DANGER = "Icons\\threat_high_danger";
    public const string ICON_CANT_RUN = "Icons\\cant_run";
    public const string ICON_EXPIRED_FOOD = "Icons\\expired_food";
    public const string ICON_FOOD_ALMOST_HUNGRY = "Icons\\food_almost_hungry";
    public const string ICON_FOOD_HUNGRY = "Icons\\food_hungry";
    public const string ICON_FOOD_STARVING = "Icons\\food_starving";
    public const string ICON_HEALING = "Icons\\healing";
    public const string ICON_IS_TARGET = "Icons\\is_target";
    public const string ICON_IS_TARGETTED = "Icons\\is_targetted";
    public const string ICON_KILLED = "Icons\\killed";
    public const string ICON_LEADER = "Icons\\leader";
    public const string ICON_MELEE_ATTACK = "Icons\\melee_attack";
    public const string ICON_MELEE_MISS = "Icons\\melee_miss";
    public const string ICON_MELEE_DAMAGE = "Icons\\melee_damage";
    public const string ICON_OUT_OF_AMMO = "Icons\\out_of_ammo";
    public const string ICON_OUT_OF_BATTERIES = "Icons\\out_of_batteries";
    public const string ICON_RANGED_ATTACK = "Icons\\ranged_attack";
    public const string ICON_RANGED_MISS = "Icons\\ranged_miss";
    public const string ICON_RANGED_DAMAGE = "Icons\\ranged_damage";
    public const string ICON_RUNNING = "Icons\\running";
    public const string ICON_ROT_ALMOST_HUNGRY = "Icons\\rot_almost_hungry";
    public const string ICON_ROT_HUNGRY = "Icons\\rot_hungry";
    public const string ICON_ROT_STARVING = "Icons\\rot_starving";
    public const string ICON_SLEEP_ALMOST_SLEEPY = "Icons\\sleep_almost_sleepy";
    public const string ICON_SLEEP_EXHAUSTED = "Icons\\sleep_exhausted";
    public const string ICON_SLEEP_SLEEPY = "Icons\\sleep_sleepy";
    public const string ICON_SPOILED_FOOD = "Icons\\spoiled_food";
    public const string ICON_TARGET = "Icons\\target";
    public const string ICON_LINE_BLOCKED = "Icons\\line_blocked";
    public const string ICON_LINE_CLEAR = "Icons\\line_clear";
    public const string ICON_LINE_BAD = "Icons\\line_bad";
    public const string ICON_SCENT_LIVING = "Icons\\scent_living";
    public const string ICON_SCENT_ZOMBIEMASTER = "Icons\\scent_zm";
    public const string ICON_SCENT_LIVING_SUPRESSOR = "Icons\\scent_living_supressor";
    public const string ICON_AGGRESSOR = "Icons\\enemy_you_aggressor";
    public const string ICON_INDIRECT_ENEMIES = "Icons\\enemy_indirect";
    public const string ICON_SELF_DEFENCE = "Icons\\enemy_you_self_defence";
    public const string ICON_TRAP_ACTIVATED = "Icons\\trap_activated";
    public const string ICON_TRAP_TRIGGERED = "Icons\\trap_triggered";
    public const string ICON_SANITY_DISTURBED = "Icons\\sanity_disturbed";
    public const string ICON_SANITY_INSANE = "Icons\\sanity_insane";
    public const string ICON_BORING_ITEM = "Icons\\boring_item";
    public const string TILE_FLOOR_ASPHALT = "Tiles\\floor_asphalt";
    public const string TILE_FLOOR_CONCRETE = "Tiles\\floor_concrete";
    public const string TILE_FLOOR_GRASS = "Tiles\\floor_grass";
    public const string TILE_FLOOR_OFFICE = "Tiles\\floor_office";
    public const string TILE_FLOOR_PLANKS = "Tiles\\floor_planks";
    public const string TILE_FLOOR_SEWER_WATER = "Tiles\\floor_sewer_water";
    public const string TILE_FLOOR_SEWER_WATER_ANIM1 = "Tiles\\floor_sewer_water_anim1";
    public const string TILE_FLOOR_SEWER_WATER_ANIM2 = "Tiles\\floor_sewer_water_anim2";
    public const string TILE_FLOOR_SEWER_WATER_ANIM3 = "Tiles\\floor_sewer_water_anim3";
    public const string TILE_FLOOR_SEWER_WATER_COVER = "Tiles\\floor_sewer_water_cover";
    public const string TILE_FLOOR_TILES = "Tiles\\floor_tiles";
    public const string TILE_FLOOR_WALKWAY = "Tiles\\floor_walkway";
    public const string TILE_ROAD_ASPHALT_NS = "Tiles\\road_asphalt_ns";
    public const string TILE_ROAD_ASPHALT_EW = "Tiles\\road_asphalt_ew";
    public const string TILE_RAIL_ES = "Tiles\\rail_ew";
    public const string TILE_WALL_BRICK = "Tiles\\wall_brick";
    public const string TILE_WALL_CHAR_OFFICE = "Tiles\\wall_char_office";
    public const string TILE_WALL_HOSPITAL = "Tiles\\wall_hospital";
    public const string TILE_WALL_SEWER = "Tiles\\wall_sewer";
    public const string TILE_WALL_STONE = "Tiles\\wall_stone";
    public const string DECO_BLOODIED_FLOOR = "Tiles\\Decoration\\bloodied_floor";
    public const string DECO_BLOODIED_WALL = "Tiles\\Decoration\\bloodied_wall";
    public const string DECO_ZOMBIE_REMAINS = "Tiles\\Decoration\\zombie_remains";
    public const string DECO_VOMIT = "Tiles\\Decoration\\vomit";
    public const string DECO_POSTERS1 = "Tiles\\Decoration\\posters1";
    public const string DECO_POSTERS2 = "Tiles\\Decoration\\posters2";
    public const string DECO_TAGS1 = "Tiles\\Decoration\\tags1";
    public const string DECO_TAGS2 = "Tiles\\Decoration\\tags2";
    public const string DECO_TAGS3 = "Tiles\\Decoration\\tags3";
    public const string DECO_TAGS4 = "Tiles\\Decoration\\tags4";
    public const string DECO_TAGS5 = "Tiles\\Decoration\\tags5";
    public const string DECO_TAGS6 = "Tiles\\Decoration\\tags6";
    public const string DECO_TAGS7 = "Tiles\\Decoration\\tags7";
    public const string DECO_SHOP_CONSTRUCTION = "Tiles\\Decoration\\shop_construction";
    public const string DECO_SHOP_GENERAL_STORE = "Tiles\\Decoration\\shop_general_store";
    public const string DECO_SHOP_GROCERY = "Tiles\\Decoration\\shop_grocery";
    public const string DECO_SHOP_GUNSHOP = "Tiles\\Decoration\\shop_gunshop";
    public const string DECO_SHOP_PHARMACY = "Tiles\\Decoration\\shop_pharmacy";
    public const string DECO_SHOP_SPORTSWEAR = "Tiles\\Decoration\\shop_sportswear";
    public const string DECO_SHOP_HUNTING = "Tiles\\Decoration\\shop_hunting";
    public const string DECO_CHAR_OFFICE = "Tiles\\Decoration\\char_office";
    public const string DECO_CHAR_FLOOR_LOGO = "Tiles\\Decoration\\char_floor_logo";
    public const string DECO_CHAR_POSTER1 = "Tiles\\Decoration\\char_poster1";
    public const string DECO_CHAR_POSTER2 = "Tiles\\Decoration\\char_poster2";
    public const string DECO_CHAR_POSTER3 = "Tiles\\Decoration\\char_poster3";
    public const string DECO_PLAYER_TAG1 = "Tiles\\Decoration\\player_tag";
    public const string DECO_PLAYER_TAG2 = "Tiles\\Decoration\\player_tag2";
    public const string DECO_PLAYER_TAG3 = "Tiles\\Decoration\\player_tag3";
    public const string DECO_PLAYER_TAG4 = "Tiles\\Decoration\\player_tag4";
    public const string DECO_ROGUEDJACK_TAG = "Tiles\\Decoration\\roguedjack";
    public const string DECO_SEWER_LADDER = "Tiles\\Decoration\\sewer_ladder";
    public const string DECO_SEWER_HOLE = "Tiles\\Decoration\\sewer_hole";
    public const string DECO_SEWERS_BUILDING = "Tiles\\Decoration\\sewers_building";
    public const string DECO_SUBWAY_BUILDING = "Tiles\\Decoration\\subway_building";
    public const string DECO_STAIRS_UP = "Tiles\\Decoration\\stairs_up";
    public const string DECO_STAIRS_DOWN = "Tiles\\Decoration\\stairs_down";
    public const string DECO_POWER_SIGN_BIG = "Tiles\\Decoration\\power_sign_big";
    public const string DECO_POLICE_STATION = "Tiles\\Decoration\\police_station";
    public const string DECO_HOSPITAL = "Tiles\\Decoration\\hospital";
    public const string OBJ_TREE = "MapObjects\\tree";
    public const string OBJ_WOODEN_DOOR_CLOSED = "MapObjects\\wooden_door_closed";
    public const string OBJ_WOODEN_DOOR_OPEN = "MapObjects\\wooden_door_open";
    public const string OBJ_WOODEN_DOOR_BROKEN = "MapObjects\\wooden_door_broken";
    public const string OBJ_GLASS_DOOR_CLOSED = "MapObjects\\glass_door_closed";
    public const string OBJ_GLASS_DOOR_OPEN = "MapObjects\\glass_door_open";
    public const string OBJ_GLASS_DOOR_BROKEN = "MapObjects\\glass_door_broken";
    public const string OBJ_CHAR_DOOR_CLOSED = "MapObjects\\dark_door_closed";
    public const string OBJ_CHAR_DOOR_OPEN = "MapObjects\\dark_door_open";
    public const string OBJ_CHAR_DOOR_BROKEN = "MapObjects\\dark_door_broken";
    public const string OBJ_WINDOW_CLOSED = "MapObjects\\window_closed";
    public const string OBJ_WINDOW_OPEN = "MapObjects\\window_open";
    public const string OBJ_WINDOW_BROKEN = "MapObjects\\window_broken";
    public const string OBJ_BENCH = "MapObjects\\bench";
    public const string OBJ_FENCE = "MapObjects\\fence";
    public const string OBJ_CAR1 = "MapObjects\\car1";
    public const string OBJ_CAR2 = "MapObjects\\car2";
    public const string OBJ_CAR3 = "MapObjects\\car3";
    public const string OBJ_CAR4 = "MapObjects\\car4";
    public const string OBJ_SHOP_SHELF = "MapObjects\\shop_shelf";
    public const string OBJ_BED = "MapObjects\\bed";
    public const string OBJ_WARDROBE = "MapObjects\\wardrobe";
    public const string OBJ_TABLE = "MapObjects\\table";
    public const string OBJ_FRIDGE = "MapObjects\\fridge";
    public const string OBJ_DRAWER = "MapObjects\\drawer";
    public const string OBJ_CHAIR = "MapObjects\\chair";
    public const string OBJ_NIGHT_TABLE = "MapObjects\\nighttable";
    public const string OBJ_CHAR_CHAIR = "MapObjects\\char_chair";
    public const string OBJ_CHAR_TABLE = "MapObjects\\char_table";
    public const string OBJ_IRON_BENCH = "MapObjects\\iron_bench";
    public const string OBJ_IRON_DOOR_OPEN = "MapObjects\\iron_door_open";
    public const string OBJ_IRON_DOOR_CLOSED = "MapObjects\\iron_door_closed";
    public const string OBJ_IRON_DOOR_BROKEN = "MapObjects\\iron_door_broken";
    public const string OBJ_IRON_FENCE = "MapObjects\\iron_fence";
    public const string OBJ_BARRELS = "MapObjects\\barrels";
    public const string OBJ_JUNK = "MapObjects\\junk";
    public const string OBJ_POWERGEN_OFF = "MapObjects\\power_generator_off";
    public const string OBJ_POWERGEN_ON = "MapObjects\\power_generator_on";
    public const string OBJ_GATE_CLOSED = "MapObjects\\gate_closed";
    public const string OBJ_GATE_OPEN = "MapObjects\\gate_open";
    public const string OBJ_BOARD = "MapObjects\\announcement_board";
    public const string OBJ_SMALL_WOODEN_FORTIFICATION = "MapObjects\\wooden_small_fortification";
    public const string OBJ_LARGE_WOODEN_FORTIFICATION = "MapObjects\\wooden_large_fortification";
    public const string OBJ_HOSPITAL_BED = "MapObjects\\hospital_bed";
    public const string OBJ_HOSPITAL_CHAIR = "MapObjects\\hospital_chair";
    public const string OBJ_HOSPITAL_NIGHT_TABLE = "MapObjects\\hospital_nighttable";
    public const string OBJ_HOSPITAL_WARDROBE = "MapObjects\\hospital_wardrobe";
    public const string OBJ_HOSPITAL_DOOR_OPEN = "MapObjects\\hospital_door_open";
    public const string OBJ_HOSPITAL_DOOR_CLOSED = "MapObjects\\hospital_door_closed";
    public const string OBJ_HOSPITAL_DOOR_BROKEN = "MapObjects\\hospital_door_broken";
    public const string PLAYER_FOLLOWER = "Actors\\player_follower";
    public const string PLAYER_FOLLOWER_TRUST = "Actors\\player_follower_trust";
    public const string PLAYER_FOLLOWER_BOND = "Actors\\player_follower_bond";
    public const string ACTOR_SKELETON = "Actors\\skeleton";
    public const string ACTOR_RED_EYED_SKELETON = "Actors\\red_eyed_skeleton";
    public const string ACTOR_RED_SKELETON = "Actors\\red_skeleton";
    public const string ACTOR_ZOMBIE = "Actors\\zombie";
    public const string ACTOR_DARK_EYED_ZOMBIE = "Actors\\dark_eyed_zombie";
    public const string ACTOR_DARK_ZOMBIE = "Actors\\dark_zombie";
    public const string ACTOR_MALE_NEOPHYTE = "Actors\\male_neophyte";
    public const string ACTOR_FEMALE_NEOPHYTE = "Actors\\female_neophyte";
    public const string ACTOR_MALE_DISCIPLE = "Actors\\male_disciple";
    public const string ACTOR_FEMALE_DISCIPLE = "Actors\\female_disciple";
    public const string ACTOR_ZOMBIE_MASTER = "Actors\\zombie_master";
    public const string ACTOR_ZOMBIE_LORD = "Actors\\zombie_lord";
    public const string ACTOR_ZOMBIE_PRINCE = "Actors\\zombie_prince";
    public const string ACTOR_RAT_ZOMBIE = "Actors\\rat_zombie";
    public const string ACTOR_SEWERS_THING = "Actors\\sewers_thing";
    public const string ACTOR_JASON_MYERS = "Actors\\jason_myers";
    public const string ACTOR_BIG_BEAR = "Actors\\big_bear";
    public const string ACTOR_FAMU_FATARU = "Actors\\famu_fataru";
    public const string ACTOR_SANTAMAN = "Actors\\santaman";
    public const string ACTOR_ROGUEDJACK = "Actors\\roguedjack";
    public const string ACTOR_DUCKMAN = "Actors\\duckman";
    public const string ACTOR_HANS_VON_HANZ = "Actors\\hans_von_hanz";
    public const string BLOODIED = "Actors\\Decoration\\bloodied";
    public const string MALE_SKIN1 = "Actors\\Decoration\\male_skin1";
    public const string MALE_SKIN2 = "Actors\\Decoration\\male_skin2";
    public const string MALE_SKIN3 = "Actors\\Decoration\\male_skin3";
    public const string MALE_SKIN4 = "Actors\\Decoration\\male_skin4";
    public const string MALE_SKIN5 = "Actors\\Decoration\\male_skin5";
    public const string MALE_HAIR1 = "Actors\\Decoration\\male_hair1";
    public const string MALE_HAIR2 = "Actors\\Decoration\\male_hair2";
    public const string MALE_HAIR3 = "Actors\\Decoration\\male_hair3";
    public const string MALE_HAIR4 = "Actors\\Decoration\\male_hair4";
    public const string MALE_HAIR5 = "Actors\\Decoration\\male_hair5";
    public const string MALE_HAIR6 = "Actors\\Decoration\\male_hair6";
    public const string MALE_HAIR7 = "Actors\\Decoration\\male_hair7";
    public const string MALE_HAIR8 = "Actors\\Decoration\\male_hair8";
    public const string MALE_SHIRT1 = "Actors\\Decoration\\male_shirt1";
    public const string MALE_SHIRT2 = "Actors\\Decoration\\male_shirt2";
    public const string MALE_SHIRT3 = "Actors\\Decoration\\male_shirt3";
    public const string MALE_SHIRT4 = "Actors\\Decoration\\male_shirt4";
    public const string MALE_SHIRT5 = "Actors\\Decoration\\male_shirt5";
    public const string MALE_PANTS1 = "Actors\\Decoration\\male_pants1";
    public const string MALE_PANTS2 = "Actors\\Decoration\\male_pants2";
    public const string MALE_PANTS3 = "Actors\\Decoration\\male_pants3";
    public const string MALE_PANTS4 = "Actors\\Decoration\\male_pants4";
    public const string MALE_PANTS5 = "Actors\\Decoration\\male_pants5";
    public const string MALE_SHOES1 = "Actors\\Decoration\\male_shoes1";
    public const string MALE_SHOES2 = "Actors\\Decoration\\male_shoes2";
    public const string MALE_SHOES3 = "Actors\\Decoration\\male_shoes3";
    public const string MALE_EYES1 = "Actors\\Decoration\\male_eyes1";
    public const string MALE_EYES2 = "Actors\\Decoration\\male_eyes2";
    public const string MALE_EYES3 = "Actors\\Decoration\\male_eyes3";
    public const string MALE_EYES4 = "Actors\\Decoration\\male_eyes4";
    public const string MALE_EYES5 = "Actors\\Decoration\\male_eyes5";
    public const string MALE_EYES6 = "Actors\\Decoration\\male_eyes6";
    public const string FEMALE_SKIN1 = "Actors\\Decoration\\female_skin1";
    public const string FEMALE_SKIN2 = "Actors\\Decoration\\female_skin2";
    public const string FEMALE_SKIN3 = "Actors\\Decoration\\female_skin3";
    public const string FEMALE_SKIN4 = "Actors\\Decoration\\female_skin4";
    public const string FEMALE_SKIN5 = "Actors\\Decoration\\female_skin5";
    public const string FEMALE_HAIR1 = "Actors\\Decoration\\female_hair1";
    public const string FEMALE_HAIR2 = "Actors\\Decoration\\female_hair2";
    public const string FEMALE_HAIR3 = "Actors\\Decoration\\female_hair3";
    public const string FEMALE_HAIR4 = "Actors\\Decoration\\female_hair4";
    public const string FEMALE_HAIR5 = "Actors\\Decoration\\female_hair5";
    public const string FEMALE_HAIR6 = "Actors\\Decoration\\female_hair6";
    public const string FEMALE_HAIR7 = "Actors\\Decoration\\female_hair7";
    public const string FEMALE_SHIRT1 = "Actors\\Decoration\\female_shirt1";
    public const string FEMALE_SHIRT2 = "Actors\\Decoration\\female_shirt2";
    public const string FEMALE_SHIRT3 = "Actors\\Decoration\\female_shirt3";
    public const string FEMALE_SHIRT4 = "Actors\\Decoration\\female_shirt4";
    public const string FEMALE_PANTS1 = "Actors\\Decoration\\female_pants1";
    public const string FEMALE_PANTS2 = "Actors\\Decoration\\female_pants2";
    public const string FEMALE_PANTS3 = "Actors\\Decoration\\female_pants3";
    public const string FEMALE_PANTS4 = "Actors\\Decoration\\female_pants4";
    public const string FEMALE_PANTS5 = "Actors\\Decoration\\female_pants5";
    public const string FEMALE_SHOES1 = "Actors\\Decoration\\female_shoes1";
    public const string FEMALE_SHOES2 = "Actors\\Decoration\\female_shoes2";
    public const string FEMALE_SHOES3 = "Actors\\Decoration\\female_shoes3";
    public const string FEMALE_EYES1 = "Actors\\Decoration\\female_eyes1";
    public const string FEMALE_EYES2 = "Actors\\Decoration\\female_eyes2";
    public const string FEMALE_EYES3 = "Actors\\Decoration\\female_eyes3";
    public const string FEMALE_EYES4 = "Actors\\Decoration\\female_eyes4";
    public const string FEMALE_EYES5 = "Actors\\Decoration\\female_eyes5";
    public const string FEMALE_EYES6 = "Actors\\Decoration\\female_eyes6";
    public const string ARMY_HELMET = "Actors\\Decoration\\army_helmet";
    public const string ARMY_PANTS = "Actors\\Decoration\\army_pants";
    public const string ARMY_SHIRT = "Actors\\Decoration\\army_shirt";
    public const string ARMY_SHOES = "Actors\\Decoration\\army_shoes";
    public const string BIKER_HAIR1 = "Actors\\Decoration\\biker_hair1";
    public const string BIKER_HAIR2 = "Actors\\Decoration\\biker_hair2";
    public const string BIKER_HAIR3 = "Actors\\Decoration\\biker_hair3";
    public const string BIKER_PANTS = "Actors\\Decoration\\biker_pants";
    public const string BIKER_SHOES = "Actors\\Decoration\\biker_shoes";
    public const string GANGSTA_HAT = "Actors\\Decoration\\gangsta_hat";
    public const string GANGSTA_PANTS = "Actors\\Decoration\\gangsta_pants";
    public const string GANGSTA_SHIRT = "Actors\\Decoration\\gangsta_shirt";
    public const string CHARGUARD_HAIR = "Actors\\Decoration\\charguard_hair";
    public const string CHARGUARD_PANTS = "Actors\\Decoration\\charguard_pants";
    public const string POLICE_HAT = "Actors\\Decoration\\police_hat";
    public const string POLICE_UNIFORM = "Actors\\Decoration\\police_uniform";
    public const string POLICE_PANTS = "Actors\\Decoration\\police_pants";
    public const string POLICE_SHOES = "Actors\\Decoration\\police_shoes";
    public const string BLACKOP_SUIT = "Actors\\Decoration\\blackop_suit";
    public const string HOSPITAL_DOCTOR_UNIFORM = "Actors\\Decoration\\hospital_doctor_uniform";
    public const string HOSPITAL_NURSE_UNIFORM = "Actors\\Decoration\\hospital_nurse_uniform";
    public const string HOSPITAL_PATIENT_UNIFORM = "Actors\\Decoration\\hospital_patient_uniform";
    public const string SURVIVOR_MALE_BANDANA = "Actors\\Decoration\\survivor_male_bandana";
    public const string SURVIVOR_FEMALE_BANDANA = "Actors\\Decoration\\survivor_female_bandana";
    public const string DOG_SKIN1 = "Actors\\Decoration\\dog_skin1";
    public const string DOG_SKIN2 = "Actors\\Decoration\\dog_skin2";
    public const string DOG_SKIN3 = "Actors\\Decoration\\dog_skin3";
    public const string ITEM_SLOT = "Items\\itemslot";
    public const string ITEM_EQUIPPED = "Items\\itemequipped";
    public const string ITEM_AMMO_LIGHT_PISTOL = "Items\\item_ammo_light_pistol";
    public const string ITEM_AMMO_HEAVY_PISTOL = "Items\\item_ammo_heavy_pistol";
    public const string ITEM_AMMO_LIGHT_RIFLE = "Items\\item_ammo_light_rifle";
    public const string ITEM_AMMO_HEAVY_RIFLE = "Items\\item_ammo_heavy_rifle";
    public const string ITEM_AMMO_SHOTGUN = "Items\\item_ammo_shotgun";
    public const string ITEM_AMMO_BOLTS = "Items\\item_ammo_bolts";
    public const string ITEM_ARMY_BODYARMOR = "Items\\item_army_bodyarmor";
    public const string ITEM_ARMY_PISTOL = "Items\\item_army_pistol";
    public const string ITEM_ARMY_RATION = "Items\\item_army_ration";
    public const string ITEM_ARMY_RIFLE = "Items\\item_army_rifle";
    public const string ITEM_BANDAGES = "Items\\item_bandages";
    public const string ITEM_BARBED_WIRE = "Items\\item_barbed_wire";
    public const string ITEM_BEAR_TRAP = "Items\\item_bear_trap";
    public const string ITEM_BASEBALL_BAT = "Items\\item_baseballbat";
    public const string ITEM_BIGBEAR_BAT = "Items\\item_bigbear_bat";
    public const string ITEM_BIG_FLASHLIGHT = "Items\\item_big_flashlight";
    public const string ITEM_BIG_FLASHLIGHT_OUT = "Items\\item_big_flashlight_out";
    public const string ITEM_BOOK = "Items\\item_book";
    public const string ITEM_BLACKOPS_GPS = "Items\\item_blackops_gps";
    public const string ITEM_CANNED_FOOD = "Items\\item_canned_food";
    public const string ITEM_CELL_PHONE = "Items\\item_cellphone";
    public const string ITEM_CHAR_LIGHT_BODYARMOR = "Items\\item_CHAR_light_bodyarmor";
    public const string ITEM_CROWBAR = "Items\\item_crowbar";
    public const string ITEM_COMBAT_KNIFE = "Items\\item_combat_knife";
    public const string ITEM_EMPTY_CAN = "Items\\item_empty_can";
    public const string ITEM_FAMU_FATARU_KATANA = "Items\\item_famu_fataru_katana";
    public const string ITEM_FLASHLIGHT = "Items\\item_flashlight";
    public const string ITEM_FLASHLIGHT_OUT = "Items\\item_flashlight_out";
    public const string ITEM_FREE_ANGELS_JACKET = "Items\\item_free_angels_jacket";
    public const string ITEM_GRENADE = "Items\\item_grenade";
    public const string ITEM_GRENADE_PRIMED = "Items\\item_grenade_primed";
    public const string ITEM_JASON_MYERS_AXE = "Items\\item_jason_myers_axe";
    public const string ITEM_GOLF_CLUB = "Items\\item_golfclub";
    public const string ITEM_GROCERIES = "Items\\item_groceries";
    public const string ITEM_HANS_VON_HANZ_PISTOL = "Items\\item_hans_von_hanz_pistol";
    public const string ITEM_HELLS_SOULS_JACKET = "Items\\item_hells_souls_jacket";
    public const string ITEM_HUGE_HAMMER = "Items\\item_huge_hammer";
    public const string ITEM_HUNTER_VEST = "Items\\item_hunter_vest";
    public const string ITEM_HUNTING_CROSSBOW = "Items\\item_hunting_crossbow";
    public const string ITEM_HUNTING_RIFLE = "Items\\item_hunting_rifle";
    public const string ITEM_IMPROVISED_CLUB = "Items\\item_improvised_club";
    public const string ITEM_IMPROVISED_SPEAR = "Items\\item_improvised_spear";
    public const string ITEM_IRON_GOLF_CLUB = "Items\\item_iron_golfclub";
    public const string ITEM_KOLT_REVOLVER = "Items\\item_kolt_revolver";
    public const string ITEM_MAGAZINE = "Items\\item_magazine";
    public const string ITEM_MEDIKIT = "Items\\item_medikit";
    public const string ITEM_PISTOL = "Items\\item_pistol";
    public const string ITEM_PILLS_ANTIVIRAL = "Items\\item_pills_antiviral";
    public const string ITEM_PILLS_BLUE = "Items\\item_pills_blue";
    public const string ITEM_PILLS_GREEN = "Items\\item_pills_green";
    public const string ITEM_PILLS_SAN = "Items\\item_pills_san";
    public const string ITEM_POLICE_JACKET = "Items\\item_police_jacket";
    public const string ITEM_POLICE_RADIO = "Items\\item_police_radio";
    public const string ITEM_POLICE_RIOT_ARMOR = "Items\\item_police_riot_armor";
    public const string ITEM_PRECISION_RIFLE = "Items\\item_precision_rifle";
    public const string ITEM_ROGUEDJACK_KEYBOARD = "Items\\item_roguedjack_keyboard";
    public const string ITEM_SANTAMAN_SHOTGUN = "Items\\item_santaman_shotgun";
    public const string ITEM_SHOTGUN = "Items\\item_shotgun";
    public const string ITEM_SHOVEL = "Items\\item_shovel";
    public const string ITEM_SMALL_HAMMER = "Items\\item_small_hammer";
    public const string ITEM_SPIKES = "Items\\item_spikes";
    public const string ITEM_SHORT_SHOVEL = "Items\\item_short_shovel";
    public const string ITEM_SPRAYPAINT = "Items\\item_spraypaint";
    public const string ITEM_SPRAYPAINT2 = "Items\\item_spraypaint2";
    public const string ITEM_SPRAYPAINT3 = "Items\\item_spraypaint3";
    public const string ITEM_SPRAYPAINT4 = "Items\\item_spraypaint4";
    public const string ITEM_STENCH_KILLER = "Items\\item_stench_killer";
    public const string ITEM_SUBWAY_BADGE = "Items\\item_subway_badge";
    public const string ITEM_TRUNCHEON = "Items\\item_truncheon";
    public const string ITEM_WOODEN_PLANK = "Items\\item_wooden_plank";
    public const string ITEM_ZTRACKER = "Items\\item_ztracker";
    public const string EFFECT_BARRICADED = "Effects\\barricaded";
    public const string EFFECT_ONFIRE = "Effects\\onFire";
    public const string UNDEF = "undef";
    public const string MAP_EXIT = "map_exit";
    public const string MINI_PLAYER_POSITION = "mini_player_position";
    public const string MINI_PLAYER_TAG1 = "mini_player_tag";
    public const string MINI_PLAYER_TAG2 = "mini_player_tag2";
    public const string MINI_PLAYER_TAG3 = "mini_player_tag3";
    public const string MINI_PLAYER_TAG4 = "mini_player_tag4";
    public const string MINI_FOLLOWER_POSITION = "mini_follower_position";
    public const string MINI_UNDEAD_POSITION = "mini_undead_position";
    public const string MINI_BLACKOPS_POSITION = "mini_blackops_position";
    public const string MINI_POLICE_POSITION = "mini_police_position";
    public const string TRACK_FOLLOWER_POSITION = "track_follower_position";
    public const string TRACK_UNDEAD_POSITION = "track_undead_position";
    public const string TRACK_BLACKOPS_POSITION = "track_blackops_position";
    public const string TRACK_POLICE_POSITION = "track_police_position";
    public const string WEATHER_RAIN1 = "weather_rain1";
    public const string WEATHER_RAIN2 = "weather_rain2";
    public const string WEATHER_HEAVY_RAIN1 = "weather_heavy_rain1";
    public const string WEATHER_HEAVY_RAIN2 = "weather_heavy_rain2";
    public const string CORPSE_DRAGGED = "corpse_dragged";
    public const string ROT1_1 = "rot1_1";
    public const string ROT1_2 = "rot1_2";
    public const string ROT2_1 = "rot2_1";
    public const string ROT2_2 = "rot2_2";
    public const string ROT3_1 = "rot3_1";
    public const string ROT3_2 = "rot3_2";
    public const string ROT4_1 = "rot4_1";
    public const string ROT4_2 = "rot4_2";
    public const string ROT5_1 = "rot5_1";
    public const string ROT5_2 = "rot5_2";
    private const string FOLDER = "Resources\\Images\\";

    public static void LoadResources(IRogueUI ui)
    {
      GameImages.Notify(ui, "icons...");
      GameImages.Load("Activities\\chasing");
      GameImages.Load("Activities\\chasing_player");
      GameImages.Load("Activities\\tracking");
      GameImages.Load("Activities\\fleeing");
      GameImages.Load("Activities\\fleeing_explosive");
      GameImages.Load("Activities\\following");
      GameImages.Load("Activities\\following_order");
      GameImages.Load("Activities\\following_player");
      GameImages.Load("Activities\\sleeping");
      GameImages.Load("Icons\\expired_food");
      GameImages.Load("Icons\\target");
      GameImages.Load("Icons\\melee_attack");
      GameImages.Load("Icons\\melee_miss");
      GameImages.Load("Icons\\melee_damage");
      GameImages.Load("Icons\\ranged_attack");
      GameImages.Load("Icons\\ranged_damage");
      GameImages.Load("Icons\\ranged_miss");
      GameImages.Load("Icons\\killed");
      GameImages.Load("Icons\\leader");
      GameImages.Load("Icons\\running");
      GameImages.Load("Icons\\cant_run");
      GameImages.Load("Icons\\can_trade");
      GameImages.Load("Icons\\out_of_ammo");
      GameImages.Load("Icons\\out_of_batteries");
      GameImages.Load("Icons\\sleep_almost_sleepy");
      GameImages.Load("Icons\\sleep_sleepy");
      GameImages.Load("Icons\\sleep_exhausted");
      GameImages.Load("Icons\\spoiled_food");
      GameImages.Load("Icons\\food_almost_hungry");
      GameImages.Load("Icons\\food_hungry");
      GameImages.Load("Icons\\food_starving");
      GameImages.Load("Icons\\line_bad");
      GameImages.Load("Icons\\line_blocked");
      GameImages.Load("Icons\\line_clear");
      GameImages.Load("Icons\\blast");
      GameImages.Load("Icons\\healing");
      GameImages.Load("Icons\\is_target");
      GameImages.Load("Icons\\is_targetted");
      GameImages.Load("Icons\\threat_danger");
      GameImages.Load("Icons\\threat_high_danger");
      GameImages.Load("Icons\\threat_safe");
      GameImages.Load("Icons\\scent_living");
      GameImages.Load("Icons\\scent_zm");
      GameImages.Load("Icons\\scent_living_supressor");
      GameImages.Load("Icons\\enemy_you_self_defence");
      GameImages.Load("Icons\\enemy_indirect");
      GameImages.Load("Icons\\enemy_you_aggressor");
      GameImages.Load("Icons\\trap_activated");
      GameImages.Load("Icons\\trap_triggered");
      GameImages.Load("Icons\\rot_almost_hungry");
      GameImages.Load("Icons\\rot_hungry");
      GameImages.Load("Icons\\rot_starving");
      GameImages.Load("Icons\\sanity_insane");
      GameImages.Load("Icons\\sanity_disturbed");
      GameImages.Load("Icons\\boring_item");
      GameImages.Notify(ui, "tiles...");
      GameImages.Load("Tiles\\floor_asphalt");
      GameImages.Load("Tiles\\floor_concrete");
      GameImages.Load("Tiles\\floor_grass");
      GameImages.Load("Tiles\\floor_office");
      GameImages.Load("Tiles\\floor_planks");
      GameImages.Load("Tiles\\floor_sewer_water");
      GameImages.Load("Tiles\\floor_sewer_water_anim1");
      GameImages.Load("Tiles\\floor_sewer_water_anim2");
      GameImages.Load("Tiles\\floor_sewer_water_anim3");
      GameImages.Load("Tiles\\floor_sewer_water_cover");
      GameImages.Load("Tiles\\floor_tiles");
      GameImages.Load("Tiles\\floor_walkway");
      GameImages.Load("Tiles\\road_asphalt_ns");
      GameImages.Load("Tiles\\road_asphalt_ew");
      GameImages.Load("Tiles\\rail_ew");
      GameImages.Load("Tiles\\wall_brick");
      GameImages.Load("Tiles\\wall_char_office");
      GameImages.Load("Tiles\\wall_hospital");
      GameImages.Load("Tiles\\wall_sewer");
      GameImages.Load("Tiles\\wall_stone");
      GameImages.Notify(ui, "tile decorations...");
      GameImages.Load("Tiles\\Decoration\\bloodied_floor");
      GameImages.Load("Tiles\\Decoration\\bloodied_wall");
      GameImages.Load("Tiles\\Decoration\\zombie_remains");
      GameImages.Load("Tiles\\Decoration\\vomit");
      GameImages.Load("Tiles\\Decoration\\posters1");
      GameImages.Load("Tiles\\Decoration\\posters2");
      GameImages.Load("Tiles\\Decoration\\tags1");
      GameImages.Load("Tiles\\Decoration\\tags2");
      GameImages.Load("Tiles\\Decoration\\tags3");
      GameImages.Load("Tiles\\Decoration\\tags4");
      GameImages.Load("Tiles\\Decoration\\tags5");
      GameImages.Load("Tiles\\Decoration\\tags6");
      GameImages.Load("Tiles\\Decoration\\tags7");
      GameImages.Load("Tiles\\Decoration\\shop_construction");
      GameImages.Load("Tiles\\Decoration\\shop_general_store");
      GameImages.Load("Tiles\\Decoration\\shop_grocery");
      GameImages.Load("Tiles\\Decoration\\shop_gunshop");
      GameImages.Load("Tiles\\Decoration\\shop_pharmacy");
      GameImages.Load("Tiles\\Decoration\\shop_sportswear");
      GameImages.Load("Tiles\\Decoration\\shop_hunting");
      GameImages.Load("Tiles\\Decoration\\char_office");
      GameImages.Load("Tiles\\Decoration\\char_floor_logo");
      GameImages.Load("Tiles\\Decoration\\char_poster1");
      GameImages.Load("Tiles\\Decoration\\char_poster2");
      GameImages.Load("Tiles\\Decoration\\char_poster3");
      GameImages.Load("Tiles\\Decoration\\player_tag");
      GameImages.Load("Tiles\\Decoration\\player_tag2");
      GameImages.Load("Tiles\\Decoration\\player_tag3");
      GameImages.Load("Tiles\\Decoration\\player_tag4");
      GameImages.Load("Tiles\\Decoration\\roguedjack");
      GameImages.Load("Tiles\\Decoration\\sewer_ladder");
      GameImages.Load("Tiles\\Decoration\\sewer_hole");
      GameImages.Load("Tiles\\Decoration\\sewers_building");
      GameImages.Load("Tiles\\Decoration\\subway_building");
      GameImages.Load("Tiles\\Decoration\\stairs_down");
      GameImages.Load("Tiles\\Decoration\\stairs_up");
      GameImages.Load("Tiles\\Decoration\\power_sign_big");
      GameImages.Load("Tiles\\Decoration\\police_station");
      GameImages.Load("Tiles\\Decoration\\hospital");
      GameImages.Notify(ui, "map objects...");
      GameImages.Load("MapObjects\\tree");
      GameImages.Load("MapObjects\\wooden_door_closed");
      GameImages.Load("MapObjects\\wooden_door_open");
      GameImages.Load("MapObjects\\wooden_door_broken");
      GameImages.Load("MapObjects\\glass_door_closed");
      GameImages.Load("MapObjects\\glass_door_open");
      GameImages.Load("MapObjects\\glass_door_broken");
      GameImages.Load("MapObjects\\dark_door_broken");
      GameImages.Load("MapObjects\\dark_door_closed");
      GameImages.Load("MapObjects\\dark_door_open");
      GameImages.Load("MapObjects\\window_closed");
      GameImages.Load("MapObjects\\window_open");
      GameImages.Load("MapObjects\\window_broken");
      GameImages.Load("MapObjects\\bench");
      GameImages.Load("MapObjects\\fence");
      GameImages.Load("MapObjects\\car1");
      GameImages.Load("MapObjects\\car2");
      GameImages.Load("MapObjects\\car3");
      GameImages.Load("MapObjects\\car4");
      GameImages.Load("MapObjects\\shop_shelf");
      GameImages.Load("MapObjects\\bed");
      GameImages.Load("MapObjects\\wardrobe");
      GameImages.Load("MapObjects\\table");
      GameImages.Load("MapObjects\\fridge");
      GameImages.Load("MapObjects\\drawer");
      GameImages.Load("MapObjects\\chair");
      GameImages.Load("MapObjects\\nighttable");
      GameImages.Load("MapObjects\\char_chair");
      GameImages.Load("MapObjects\\char_table");
      GameImages.Load("MapObjects\\iron_bench");
      GameImages.Load("MapObjects\\iron_fence");
      GameImages.Load("MapObjects\\iron_door_broken");
      GameImages.Load("MapObjects\\iron_door_closed");
      GameImages.Load("MapObjects\\iron_door_open");
      GameImages.Load("MapObjects\\barrels");
      GameImages.Load("MapObjects\\junk");
      GameImages.Load("MapObjects\\power_generator_off");
      GameImages.Load("MapObjects\\power_generator_on");
      GameImages.Load("MapObjects\\gate_closed");
      GameImages.Load("MapObjects\\gate_open");
      GameImages.Load("MapObjects\\announcement_board");
      GameImages.Load("MapObjects\\wooden_small_fortification");
      GameImages.Load("MapObjects\\wooden_large_fortification");
      GameImages.Load("MapObjects\\hospital_bed");
      GameImages.Load("MapObjects\\hospital_chair");
      GameImages.Load("MapObjects\\hospital_door_broken");
      GameImages.Load("MapObjects\\hospital_door_closed");
      GameImages.Load("MapObjects\\hospital_door_open");
      GameImages.Load("MapObjects\\hospital_nighttable");
      GameImages.Load("MapObjects\\hospital_wardrobe");
      GameImages.Notify(ui, "actors...");
      GameImages.Load("Actors\\player_follower");
      GameImages.Load("Actors\\player_follower_trust");
      GameImages.Load("Actors\\player_follower_bond");
      GameImages.Load("Actors\\skeleton");
      GameImages.Load("Actors\\red_eyed_skeleton");
      GameImages.Load("Actors\\red_skeleton");
      GameImages.Load("Actors\\zombie");
      GameImages.Load("Actors\\dark_eyed_zombie");
      GameImages.Load("Actors\\dark_zombie");
      GameImages.Load("Actors\\male_neophyte");
      GameImages.Load("Actors\\female_neophyte");
      GameImages.Load("Actors\\male_disciple");
      GameImages.Load("Actors\\female_disciple");
      GameImages.Load("Actors\\zombie_master");
      GameImages.Load("Actors\\zombie_lord");
      GameImages.Load("Actors\\zombie_prince");
      GameImages.Load("Actors\\rat_zombie");
      GameImages.Load("Actors\\sewers_thing");
      GameImages.Load("Actors\\jason_myers");
      GameImages.Load("Actors\\big_bear");
      GameImages.Load("Actors\\famu_fataru");
      GameImages.Load("Actors\\santaman");
      GameImages.Load("Actors\\roguedjack");
      GameImages.Load("Actors\\duckman");
      GameImages.Load("Actors\\hans_von_hanz");
      GameImages.Notify(ui, "actor decorations...");
      GameImages.Load("Actors\\Decoration\\bloodied");
      GameImages.Load("Actors\\Decoration\\male_skin1");
      GameImages.Load("Actors\\Decoration\\male_skin2");
      GameImages.Load("Actors\\Decoration\\male_skin3");
      GameImages.Load("Actors\\Decoration\\male_skin4");
      GameImages.Load("Actors\\Decoration\\male_skin5");
      GameImages.Load("Actors\\Decoration\\male_shirt1");
      GameImages.Load("Actors\\Decoration\\male_shirt2");
      GameImages.Load("Actors\\Decoration\\male_shirt3");
      GameImages.Load("Actors\\Decoration\\male_shirt4");
      GameImages.Load("Actors\\Decoration\\male_shirt5");
      GameImages.Load("Actors\\Decoration\\male_hair1");
      GameImages.Load("Actors\\Decoration\\male_hair2");
      GameImages.Load("Actors\\Decoration\\male_hair3");
      GameImages.Load("Actors\\Decoration\\male_hair4");
      GameImages.Load("Actors\\Decoration\\male_hair5");
      GameImages.Load("Actors\\Decoration\\male_hair6");
      GameImages.Load("Actors\\Decoration\\male_hair7");
      GameImages.Load("Actors\\Decoration\\male_hair8");
      GameImages.Load("Actors\\Decoration\\male_pants1");
      GameImages.Load("Actors\\Decoration\\male_pants2");
      GameImages.Load("Actors\\Decoration\\male_pants3");
      GameImages.Load("Actors\\Decoration\\male_pants4");
      GameImages.Load("Actors\\Decoration\\male_pants5");
      GameImages.Load("Actors\\Decoration\\male_shoes1");
      GameImages.Load("Actors\\Decoration\\male_shoes2");
      GameImages.Load("Actors\\Decoration\\male_shoes3");
      GameImages.Load("Actors\\Decoration\\male_eyes1");
      GameImages.Load("Actors\\Decoration\\male_eyes2");
      GameImages.Load("Actors\\Decoration\\male_eyes3");
      GameImages.Load("Actors\\Decoration\\male_eyes4");
      GameImages.Load("Actors\\Decoration\\male_eyes5");
      GameImages.Load("Actors\\Decoration\\male_eyes6");
      GameImages.Load("Actors\\Decoration\\female_skin1");
      GameImages.Load("Actors\\Decoration\\female_skin2");
      GameImages.Load("Actors\\Decoration\\female_skin3");
      GameImages.Load("Actors\\Decoration\\female_skin4");
      GameImages.Load("Actors\\Decoration\\female_skin5");
      GameImages.Load("Actors\\Decoration\\female_shirt1");
      GameImages.Load("Actors\\Decoration\\female_shirt2");
      GameImages.Load("Actors\\Decoration\\female_shirt3");
      GameImages.Load("Actors\\Decoration\\female_shirt4");
      GameImages.Load("Actors\\Decoration\\female_hair1");
      GameImages.Load("Actors\\Decoration\\female_hair2");
      GameImages.Load("Actors\\Decoration\\female_hair3");
      GameImages.Load("Actors\\Decoration\\female_hair4");
      GameImages.Load("Actors\\Decoration\\female_hair5");
      GameImages.Load("Actors\\Decoration\\female_hair6");
      GameImages.Load("Actors\\Decoration\\female_hair7");
      GameImages.Load("Actors\\Decoration\\female_pants1");
      GameImages.Load("Actors\\Decoration\\female_pants2");
      GameImages.Load("Actors\\Decoration\\female_pants3");
      GameImages.Load("Actors\\Decoration\\female_pants4");
      GameImages.Load("Actors\\Decoration\\female_pants5");
      GameImages.Load("Actors\\Decoration\\female_shoes1");
      GameImages.Load("Actors\\Decoration\\female_shoes2");
      GameImages.Load("Actors\\Decoration\\female_shoes3");
      GameImages.Load("Actors\\Decoration\\female_eyes1");
      GameImages.Load("Actors\\Decoration\\female_eyes2");
      GameImages.Load("Actors\\Decoration\\female_eyes3");
      GameImages.Load("Actors\\Decoration\\female_eyes4");
      GameImages.Load("Actors\\Decoration\\female_eyes5");
      GameImages.Load("Actors\\Decoration\\female_eyes6");
      GameImages.Load("Actors\\Decoration\\army_helmet");
      GameImages.Load("Actors\\Decoration\\army_pants");
      GameImages.Load("Actors\\Decoration\\army_shirt");
      GameImages.Load("Actors\\Decoration\\army_shoes");
      GameImages.Load("Actors\\Decoration\\biker_hair1");
      GameImages.Load("Actors\\Decoration\\biker_hair2");
      GameImages.Load("Actors\\Decoration\\biker_hair3");
      GameImages.Load("Actors\\Decoration\\biker_pants");
      GameImages.Load("Actors\\Decoration\\biker_shoes");
      GameImages.Load("Actors\\Decoration\\gangsta_hat");
      GameImages.Load("Actors\\Decoration\\gangsta_pants");
      GameImages.Load("Actors\\Decoration\\gangsta_shirt");
      GameImages.Load("Actors\\Decoration\\charguard_hair");
      GameImages.Load("Actors\\Decoration\\charguard_pants");
      GameImages.Load("Actors\\Decoration\\police_hat");
      GameImages.Load("Actors\\Decoration\\police_pants");
      GameImages.Load("Actors\\Decoration\\police_shoes");
      GameImages.Load("Actors\\Decoration\\police_uniform");
      GameImages.Load("Actors\\Decoration\\blackop_suit");
      GameImages.Load("Actors\\Decoration\\hospital_doctor_uniform");
      GameImages.Load("Actors\\Decoration\\hospital_nurse_uniform");
      GameImages.Load("Actors\\Decoration\\hospital_patient_uniform");
      GameImages.Load("Actors\\Decoration\\survivor_female_bandana");
      GameImages.Load("Actors\\Decoration\\survivor_male_bandana");
      GameImages.Load("Actors\\Decoration\\dog_skin1");
      GameImages.Load("Actors\\Decoration\\dog_skin2");
      GameImages.Load("Actors\\Decoration\\dog_skin3");
      GameImages.Notify(ui, "items...");
      GameImages.Load("Items\\itemslot");
      GameImages.Load("Items\\itemequipped");
      GameImages.Load("Items\\item_ammo_bolts");
      GameImages.Load("Items\\item_ammo_heavy_pistol");
      GameImages.Load("Items\\item_ammo_heavy_rifle");
      GameImages.Load("Items\\item_ammo_light_pistol");
      GameImages.Load("Items\\item_ammo_light_rifle");
      GameImages.Load("Items\\item_ammo_shotgun");
      GameImages.Load("Items\\item_army_bodyarmor");
      GameImages.Load("Items\\item_army_pistol");
      GameImages.Load("Items\\item_army_ration");
      GameImages.Load("Items\\item_army_rifle");
      GameImages.Load("Items\\item_bandages");
      GameImages.Load("Items\\item_barbed_wire");
      GameImages.Load("Items\\item_baseballbat");
      GameImages.Load("Items\\item_bear_trap");
      GameImages.Load("Items\\item_bigbear_bat");
      GameImages.Load("Items\\item_big_flashlight");
      GameImages.Load("Items\\item_big_flashlight_out");
      GameImages.Load("Items\\item_blackops_gps");
      GameImages.Load("Items\\item_book");
      GameImages.Load("Items\\item_canned_food");
      GameImages.Load("Items\\item_cellphone");
      GameImages.Load("Items\\item_CHAR_light_bodyarmor");
      GameImages.Load("Items\\item_combat_knife");
      GameImages.Load("Items\\item_crowbar");
      GameImages.Load("Items\\item_empty_can");
      GameImages.Load("Items\\item_famu_fataru_katana");
      GameImages.Load("Items\\item_flashlight");
      GameImages.Load("Items\\item_flashlight_out");
      GameImages.Load("Items\\item_free_angels_jacket");
      GameImages.Load("Items\\item_golfclub");
      GameImages.Load("Items\\item_grenade");
      GameImages.Load("Items\\item_grenade_primed");
      GameImages.Load("Items\\item_groceries");
      GameImages.Load("Items\\item_hells_souls_jacket");
      GameImages.Load("Items\\item_huge_hammer");
      GameImages.Load("Items\\item_hunter_vest");
      GameImages.Load("Items\\item_hunting_crossbow");
      GameImages.Load("Items\\item_hunting_rifle");
      GameImages.Load("Items\\item_improvised_club");
      GameImages.Load("Items\\item_improvised_spear");
      GameImages.Load("Items\\item_iron_golfclub");
      GameImages.Load("Items\\item_jason_myers_axe");
      GameImages.Load("Items\\item_hans_von_hanz_pistol");
      GameImages.Load("Items\\item_kolt_revolver");
      GameImages.Load("Items\\item_magazine");
      GameImages.Load("Items\\item_medikit");
      GameImages.Load("Items\\item_pills_antiviral");
      GameImages.Load("Items\\item_pills_blue");
      GameImages.Load("Items\\item_pills_green");
      GameImages.Load("Items\\item_pills_san");
      GameImages.Load("Items\\item_pistol");
      GameImages.Load("Items\\item_police_jacket");
      GameImages.Load("Items\\item_police_radio");
      GameImages.Load("Items\\item_police_riot_armor");
      GameImages.Load("Items\\item_precision_rifle");
      GameImages.Load("Items\\item_roguedjack_keyboard");
      GameImages.Load("Items\\item_santaman_shotgun");
      GameImages.Load("Items\\item_shotgun");
      GameImages.Load("Items\\item_shovel");
      GameImages.Load("Items\\item_small_hammer");
      GameImages.Load("Items\\item_short_shovel");
      GameImages.Load("Items\\item_spikes");
      GameImages.Load("Items\\item_spraypaint");
      GameImages.Load("Items\\item_spraypaint2");
      GameImages.Load("Items\\item_spraypaint3");
      GameImages.Load("Items\\item_spraypaint4");
      GameImages.Load("Items\\item_stench_killer");
      GameImages.Load("Items\\item_subway_badge");
      GameImages.Load("Items\\item_truncheon");
      GameImages.Load("Items\\item_wooden_plank");
      GameImages.Load("Items\\item_ztracker");
      GameImages.Notify(ui, "effects...");
      GameImages.Load("Effects\\barricaded");
      GameImages.Load("Effects\\onFire");
      GameImages.Notify(ui, "misc...");
      GameImages.Load("undef");
      GameImages.Load("map_exit");
      GameImages.Load("mini_blackops_position");
      GameImages.Load("mini_follower_position");
      GameImages.Load("mini_player_position");
      GameImages.Load("mini_player_tag");
      GameImages.Load("mini_player_tag2");
      GameImages.Load("mini_player_tag3");
      GameImages.Load("mini_player_tag4");
      GameImages.Load("mini_police_position");
      GameImages.Load("mini_undead_position");
      GameImages.Load("track_blackops_position");
      GameImages.Load("track_follower_position");
      GameImages.Load("track_police_position");
      GameImages.Load("track_undead_position");
      GameImages.Load("weather_rain1");
      GameImages.Load("weather_rain2");
      GameImages.Load("weather_heavy_rain1");
      GameImages.Load("weather_heavy_rain2");
      GameImages.Load("rot1_1");
      GameImages.Load("rot1_2");
      GameImages.Load("rot2_1");
      GameImages.Load("rot2_2");
      GameImages.Load("rot3_1");
      GameImages.Load("rot3_2");
      GameImages.Load("rot4_1");
      GameImages.Load("rot4_2");
      GameImages.Load("rot5_1");
      GameImages.Load("rot5_2");
      GameImages.Load("corpse_dragged");
      GameImages.Notify(ui, "done!");
    }

    private static void Load(string id)
    {
      string filename = "Resources\\Images\\" + id + ".png";
      try {
        Bitmap img = new Bitmap(filename);
        GameImages.s_Images.Add(id, img);
        GameImages.s_GrayLevelImages.Add(id, GameImages.MakeGrayLevel(img));
      } catch (Exception ex) {
        throw new ArgumentException("coud not load image id=" + id + "; file=" + filename);
      }
    }

    private static Image MakeGrayLevel(Bitmap img)
    {
      Bitmap bitmap = new Bitmap((Image) img);
      for (int x = 0; x < bitmap.Width; ++x) {
        for (int y = 0; y < bitmap.Height; ++y) {
          Color pixel = img.GetPixel(x, y);
          int num = (int) (140.25 * (double) pixel.GetBrightness());
          bitmap.SetPixel(x, y, Color.FromArgb((int) pixel.A, num, num, num));
        }
      }
      return (Image) bitmap;
    }

    private static void Notify(IRogueUI ui, string stage)
    {
      ui.UI_Clear(Color.Black);
      ui.UI_DrawStringBold(Color.White, "Loading resources: " + stage, 0, 0, new Color?());
      ui.UI_Repaint();
    }

    public static Image Get(string imageID)
    {
      Image image;
      if (GameImages.s_Images.TryGetValue(imageID, out image))
        return image;
      return GameImages.s_Images["undef"];
    }

    public static Image GetGrayLevel(string imageID)
    {
      Image image;
      if (GameImages.s_GrayLevelImages.TryGetValue(imageID, out image))
        return image;
      return GameImages.s_GrayLevelImages["undef"];
    }
  }
}
